name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache osxcross toolchain
        uses: actions/cache@v3
        with:
          path: |
            ./osxcross/target/
          key: ${{ runner.os }}-osxcross-${{ hashFiles('ci-setup.sh') }}
      - name: Make CI script executable
        run: chmod +x ./ci-setup.sh
      - name: Execute CI script
        run: ./ci-setup.sh
      - name: Add osxcross to PATH
        run: echo "$(pwd)/osxcross/target/bin" >> $GITHUB_PATH
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
        env:
          CSJ_FULL_BUILD: 1